### ISSUE TITLE
ImportError: No module named dylutils

### ISSUE THREAD

**Issue by teroz** [CSD-Public/stonix#2]
I was unable to install the module on ubuntu 15.04
sudo pip install dylutils
Could not find any downloads that satisfy the requirement dylutils

**Comment by fgeek** [comment]
This is probably related [stonixutilityfunctions.py#L32](https://github.com/CSD-Public/stonix/blob/master/src/stonix_resources/stonixutilityfunctions.py#L32)

```
  32 #               Filename          $RCSfile: dylutils.py,v $
  33 #               Description       Utility functions for STONIX
```

The code trying to import this is in [DisableAutoLogin.py#L45](https://github.com/CSD-Public/stonix/blob/master/src/stonix_resources/rules/DisableAutoLogin.py#L45)

```
from ..dylutils import *
```

and there is no such Python module in PyPi.

**Comment by roynielsen17** [comment]
My apologies, the fix is in the develop branch.  pending approval, I will merge to master by Monday.  In the mean time, you may safely remove that import line without consequence.

Regards,
-Roy

**Comment by amrset** [comment]
Please try again, I've merged the change back onto master.

Regards,
-Roy

**Comment by teroz** [comment]
Awesome will do thank you

**Comment by amrset** [comment]
teroz - have you had a chance to check it out?  If this fix fixes the problem for you, could you close the issue?

**Comment by teroz** [comment]
fixed thank you
